# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84fad5c5d4e286f72f633d523c98fa5fca4c5df610564f309036ef4ae189e043d36748d737ade700b9f303332f6af0294d8e6180836400968c08e771ceb72c0e

test:
  secret_key_base: d04d90d881ff34fefdc062ca91b8acd8c3c1af9e5ca42dcf03c2dff58090b02b97a6421efd946f1d8a02883e26d46cb8a98e9a29ede2c53fa8dae3da0fdfd258

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
